# Homebrew Formula for EnvVault CLI
# Auto-generated by CI/CD on release

class Envault < Formula
  desc "Secure, local-first environment variable management"
  homepage "https://envault.net"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dj-pearson/vault-verse/releases/download/v0.1.6/envault-darwin-arm64"
      sha256 "6499fc604cdca3913ce1a0223b80615f885ba61f5af8f3c01eaad92631abe919"
    else
      url "https://github.com/dj-pearson/vault-verse/releases/download/v0.1.6/envault-darwin-amd64"
      sha256 "fdf0bcd1d4e79bb6e28ea9859301eea8a42256ae6d90e9a27e8d587e8ef5f9a2"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/dj-pearson/vault-verse/releases/download/v0.1.6/envault-linux-arm64"
      sha256 "d98a353e35a058a2e9422fdaf5ee40848d1d7c844811527f46ec1a9af8a6aa05"
    else
      url "https://github.com/dj-pearson/vault-verse/releases/download/v0.1.6/envault-linux-amd64"
      sha256 "86af487722bdc8bdea483a50cb479760cf7f28e299ba123c7aed925ed9cadc41"
    end
  end

  def install
    bin.install "envault-#{OS.kernel_name.downcase}-#{Hardware::CPU.arch}" => "envault"

    # Generate shell completions
    output = Utils.safe_popen_read("#{bin}/envault", "completion", "bash")
    (bash_completion/"envault").write output

    output = Utils.safe_popen_read("#{bin}/envault", "completion", "zsh")
    (zsh_completion/"_envault").write output

    output = Utils.safe_popen_read("#{bin}/envault", "completion", "fish")
    (fish_completion/"envault.fish").write output
  end

  test do
    system "#{bin}/envault", "--version"
    assert_match "envault version", shell_output("#{bin}/envault --version")
  end
end
