# Homebrew Formula for EnvVault CLI
# Auto-generated by CI/CD on release

class Envault < Formula
  desc "Secure, local-first environment variable management"
  homepage "https://envault.net"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dj-pearson/vault-verse/releases/download/v0.1.0/envault-darwin-arm64"
      sha256 "0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5"
    else
      url "https://github.com/dj-pearson/vault-verse/releases/download/v0.1.0/envault-darwin-amd64"
      sha256 "0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/dj-pearson/vault-verse/releases/download/v0.1.0/envault-linux-arm64"
      sha256 "0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5"
    else
      url "https://github.com/dj-pearson/vault-verse/releases/download/v0.1.0/envault-linux-amd64"
      sha256 "0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5"
    end
  end

  def install
    bin.install "envault-#{OS.kernel_name.downcase}-#{Hardware::CPU.arch}" => "envault"

    # Generate shell completions
    output = Utils.safe_popen_read("#{bin}/envault", "completion", "bash")
    (bash_completion/"envault").write output

    output = Utils.safe_popen_read("#{bin}/envault", "completion", "zsh")
    (zsh_completion/"_envault").write output

    output = Utils.safe_popen_read("#{bin}/envault", "completion", "fish")
    (fish_completion/"envault.fish").write output
  end

  test do
    system "#{bin}/envault", "--version"
    assert_match "envault version", shell_output("#{bin}/envault --version")
  end
end
